### ISSUE TITLE
Maintain and release

### ISSUE THREAD

**Issue by hasegeli** [ifduyue/polysh#1]
We decided to maintain the project at InnoGames System Administration [1].  It is currently ported to Python 3, and we are committed to support the users.  We have contacted the original author, but you actually seem to be the owner on PyPi.  Could you please transfer it to us so we can release new version?  My username on PyPi is "hasegeli".

[1] https://github.com/innogames/polysh

**Comment by ifduyue** [comment]
@hasegeli Hello, I've added you as an owner.

**Comment by hasegeli** [comment]
Thank you.  I will also contact GitHub support to change the direction of the fork on GitHub, so that the contributions on the repository would appear on contributors profiles, if you don't mind.

**Comment by ifduyue** [comment]
@hasegeli no problem, go ahead.

**Comment by hasegeli** [comment]
GitHub support asked me to:

> Could you ask @ifduyue to email support@github.com from their verified email address and confirm this? We'd like to hear from them directly before making changes to their repository.

It would be great if you can.

**Comment by ifduyue** [comment]
Confirmation sent, let's wait

**Comment by hasegeli** [comment]
It is done.  Thank you for your cooperation.
